[package]
name = "wijc"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
clap = { version = "4.5.37", features = ["derive"] }
rand = "0.9.1"
wij_core = { path = "../wij_core" }
wij_codegen = { path = "../wij_codegen" }
